<div>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-2205808977421463";
/* footer_small */
google_ad_slot = "7877496925";
google_ad_width = 234;
google_ad_height = 60;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
<div>
<hr />
</div>
<div class="small"> 
    Created by {{author}}
    Version: Dev - 1.2.7
    <br />
    App was built on: Fri Feb  4 15:14:25 CET 2011
</div>